comp_wb_pkg:
	vlog $(ECE745_PROJECT_HOME)/verification_ip/interface_packages/wb_pkg/src/wb_if.sv
	vlog +incdir+$(ECE745_PROJECT_HOME)/verification_ip/interface_packages/wb_pkg $(ECE745_PROJECT_HOME)/verification_ip/interface_packages/wb_pkg/wb_pkg.sv
comp_wb_pkg_sil:
	vlog $(ECE745_PROJECT_HOME)/verification_ip/interface_packages/wb_pkg/src/wb_if.sv > /dev/null
	vlog +incdir+$(ECE745_PROJECT_HOME)/verification_ip/interface_packages/wb_pkg $(ECE745_PROJECT_HOME)/verification_ip/interface_packages/wb_pkg/wb_pkg.sv > /dev/null
	