comp_i2cmb_env:
	vlog +incdir+$(ECE745_PROJECT_HOME)/verification_ip/environment_packages/i2cmb_env_pkg $(ECE745_PROJECT_HOME)/verification_ip/environment_packages/i2cmb_env_pkg/i2cmb_env_pkg.sv

comp_i2cmb_env_sil:
	vlog +incdir+$(ECE745_PROJECT_HOME)/verification_ip/environment_packages/i2cmb_env_pkg $(ECE745_PROJECT_HOME)/verification_ip/environment_packages/i2cmb_env_pkg/i2cmb_env_pkg.sv > /dev/null
	