comp_ncsu_pkg:
	vlog +incdir+$(ECE745_PROJECT_HOME)/verification_ip/ncsu_pkg $(ECE745_PROJECT_HOME)/verification_ip/ncsu_pkg/ncsu_pkg.sv

comp_ncsu_pkg_sil:
	vlog +incdir+$(ECE745_PROJECT_HOME)/verification_ip/ncsu_pkg $(ECE745_PROJECT_HOME)/verification_ip/ncsu_pkg/ncsu_pkg.sv > /dev/null
	